feat(92-cruft-update): cruft autoupdate action

diff --git a/cruft/create/action.yml b/cruft/create/action.yml
--- a/cruft/create/action.yml
+++ b/cruft/create/action.yml
@@ -172,24 +172,24 @@ runs:
         private-key: "${{ inputs.github-app-private-key }}"
         owner: "${{ github.repository_owner }}"
         repositories: "${{ github.event.repository.name }}"
-        permission-workflows: "write"
-        permission-contents: "write"
+        # permission-workflows: "write"
+        # permission-contents: "write"
         # permission-pull-requests: "write"
 
-    - name: Configure Git Authentication
-      shell: bash
-      env:
-        APP_TOKEN: ${{ steps.github-app-token-write.outputs.token }}
-        INPUT_TOKEN: ${{ inputs.token }}
-      run: |
-        if [ -n "$APP_TOKEN" ]; then
-          git config --global url."https://x-access-token:${APP_TOKEN}@github.com/".insteadOf "https://github.com/"
-        elif [ -n "$INPUT_TOKEN" ]; then
-          git config --global url."https://x-access-token:${INPUT_TOKEN}@github.com/".insteadOf "https://github.com/"
-        else
-          echo "Error: No token provided for authentication"
-          exit 1
-        fi
+    # - name: Configure Git Authentication
+    #   shell: bash
+    #   env:
+    #     APP_TOKEN: ${{ steps.github-app-token-write.outputs.token }}
+    #     INPUT_TOKEN: ${{ inputs.token }}
+    #   run: |
+    #     if [ -n "$APP_TOKEN" ]; then
+    #       git config --global url."https://x-access-token:${APP_TOKEN}@github.com/".insteadOf "https://github.com/"
+    #     elif [ -n "$INPUT_TOKEN" ]; then
+    #       git config --global url."https://x-access-token:${INPUT_TOKEN}@github.com/".insteadOf "https://github.com/"
+    #     else
+    #       echo "Error: No token provided for authentication"
+    #       exit 1
+    #     fi
 
     - name: Variables
       shell: bash
