feat(92-cruft-update): cruft autoupdate action

diff --git a/cruft/authenticate/action.yml b/cruft/authenticate/action.yml
--- a/cruft/authenticate/action.yml
+++ b/cruft/authenticate/action.yml
@@ -97,19 +97,32 @@ inputs:
     default: ""
 
   token:
-    required: true
+    required: false
     description: "GitHub repository token with read and write permissions for contents, pull requests, and issues, plus read-only access to security events."
+    default: ""
 
 runs:
   using: composite
   steps:
     - name: Token
       id: github-app-token
+      if: inputs.github-app-id != '' && inputs.github-app-private-key != ''
       uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
       with:
         app-id: ${{ inputs.github-app-id }}
         private-key: ${{ inputs.github-app-private-key }}
 
-    - name: Directory
+    - name: Configure
       shell: bash
-      run: git config --global url."https://x-access-token:${{ steps.github-app-token.outputs.token }}@github.com/".insteadOf "https://github.com/"
+      env:
+        APP_TOKEN: ${{ steps.github-app-token.outputs.token }}
+        INPUT_TOKEN: ${{ inputs.token }}
+      run: |
+        if [ -n "$APP_TOKEN" ]; then
+          git config --global url."https://x-access-token:${APP_TOKEN}@github.com/".insteadOf "https://github.com/"
+        elif [ -n "$INPUT_TOKEN" ]; then
+          git config --global url."https://x-access-token:${INPUT_TOKEN}@github.com/".insteadOf "https://github.com/"
+        else
+          echo "Error: No token provided for authentication!"
+          exit 1
+        fi
