feat(10): added SLSA check

diff --git a/.github/workflows/slsa.yml b/.github/workflows/slsa.yml
--- a/.github/workflows/slsa.yml
+++ b/.github/workflows/slsa.yml
@@ -45,8 +45,6 @@ jobs:
 
       - name: ⛓️ SLSA
         uses: ministryofjustice/devsecops-actions/sca/slsa@559ec2408860d9237cc472a5710e61c1c2187ffa
-        with:
-          security-patch-package-exclusion: "safe-chain-test"
 
       - name: Node
         uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
@@ -57,4 +55,18 @@ jobs:
 
       - name: Install
         shell: bash
-        run: npm install safe-chain-test
+        run: |
+          set +e
+
+          # Install malicious test package
+          # Exit with non-zero code
+          npm install safe-chain-test
+
+          # Exit code
+          EXIT_CODE=$?
+
+          if [ $EXIT_CODE -eq 0 ]; then
+            echo "❌ SLSA check failed.";
+          else
+            echo "✅ SLSA check passed."
+          fi
